# Copyright 2021, Proofcraft Pty Ltd
#
# SPDX-License-Identifier: BSD-2-Clause

name: 'seL4 Benchmark Builds'
description: |
  Runs sel4bench builds for all hardware test platforms.
author: Gerwin Klein <gerwin.klein@proofcraft.systems>

inputs:
  arch:
    description: Comma separated list of architectures to filter test configs on.
    required: false
  march:
    description: Comma separated list of march flags to filter test configs on.
    required: false
  mode:
    description: Comma separated list of modes (32/64) to filter test configs on.
    required: false
  xml:
    description: sel4bench xml manifest to test
    required: false

runs:
  using: 'docker'
  image: 'docker://sel4/sel4bench:latest'
