# Copyright 2021, Proofcraft Pty Ltd
#
# SPDX-License-Identifier: BSD-2-Clause

name: 'CAmkES VM Hardware Tests'
description: |
  The CAmkES VM hardware test suite. Depends on images built in the camkes-vm job.
author: Gerwin Klein <gerwin.klein@proofcraft.systems>

inputs:
  name:
    description: 'Name of the build to run (for matrix builds)'
    required: false
  march:
    description: 'Comma-separated list of march to filter on (for matrix builds)'
    required: false
  index:
    description: job index in matrix build
    required: true
  action_name:
    description: 'internal -- do not use'
    required: false
    default: 'camkes-vm-hw'

runs:
  using: 'node12'
  main: '../js/index.js'
  post: '../js/post.js'
