# Copyright 2020, Data61, CSIRO (ABN 41 687 119 230)
#
# SPDX-License-Identifier: BSD-2-Clause

name: 'Compile standalone kernel'
description: |
  Attempts to compile the verified configurations of the stand-alone
  seL4 kernel.
author: Luke Mondy <luke.mondy@data61.csiro.au>

inputs:
  ARCH:
    description: 'Architecture to test. One of ARM, ARM_HYP, AARCH64, RISCV64, X64'
    required: true

  COMPILER:
    description: 'Which compiler suite to use. One of gcc, llvm'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
