# Copyright 2020, Data61, CSIRO (ABN 41 687 119 230)
#
# SPDX-License-Identifier: BSD-2-Clause

name: 'Style'
description: 'Runs check for bashisms on shell scripts'
author: Gerwin Klein <kleing@unsw.edu.au>

inputs:
  token:
    description: 'GitHub token for read access to repository'
    required: false
  action_name:
    description: 'internal -- do not use'
    required: false
    default: 'bashisms'

runs:
  using: 'node12'
  main: '../js/index.js'
