# Copyright 2021, Proofcraft Pty Ltd
#
# SPDX-License-Identifier: BSD-2-Clause

name: 'RumpRun Hello World'
description: |
  The rumprun hello-world test.
author: Gerwin Klein <gerwin.klein@proofcraft.systems>

inputs:
  name:
    description: Comma separated list of build names to filter build list on.
    required: false
  req:
    description: Comma separated list of hardware to build for.
    required: false
  mode:
    description: Comma separated list of modes to build for. One of `{32, 64}.`
    required: false

runs:
  using: 'docker'
  image: 'docker://sel4/rump-hello:latest'
