# Copyright 2021, Proofcraft Pty Ltd
# Copyright 2026, UNSW
#
# SPDX-License-Identifier: BSD-2-Clause

name: 'microkit/Hardware Builds'
description: |
  Does microkit hw builds.
author: Julia Vassiliki <julia.vassiliki@unsw.edu.au>

inputs:
  board:
    description: Comma separated list of microkit boards (MICROKIT_BOARD) to run the test for.
    required: true
  config:
    description: Comma separated list of microkit configs (MICROKIT_CONFIG) to run the test for.
    required: false
  march:
    description: Comma separated list of platform marches (from platforms.yml) to run the test for.
    required: false
  index:
    description: job index in matrix build
    required: true
  action_name:
    description: 'internal -- do not use'
    required: false
    default: 'microkit-hw-build'

runs:
  using: 'node24'
  main: '../js/index.js'
