# Copyright 2020, Data61, CSIRO (ABN 41 687 119 230)
#
# SPDX-License-Identifier: BSD-2-Clause

name: 'Link Check'
description: 'Check links in .md and .html files'
author: Gerwin Klein <gerwin.klein@csiro.au>

inputs:
  dir:
    description: 'Directory to check (recursively)'
    default: .
  exclude:
    description: 'grep regex on path for which files to exclude'
  timeout:
    description: 'Timeout for link response'
  doc_root:
    description: 'Document root for absolute links'
  num_requests:
    description: 'Maximum number of concurrent requests'
  verbose:
    description: 'Print more information if set (default unset)'

runs:
  using: 'docker'
  image: 'docker://sel4/link-check:latest'
