# Copyright 2020, Data61, CSIRO (ABN 41 687 119 230)
#
# SPDX-License-Identifier: BSD-2-Clause

FROM trustworthysystems/sel4-riscv:latest

COPY compile_sel4test.sh /compile_sel4test.sh

ENTRYPOINT ["/compile_sel4test.sh"]
