# Copyright 2021, Proofcraft Pty Ltd
#
# SPDX-License-Identifier: BSD-2-Clause

name: 'CAmkES Hardware Test'
description: |
  The hardware runs for the CAmkES test suite.
  Depends on previously built impages.
author: Gerwin Klein <gerwin.klein@proofcraft.systems>

inputs:
  name:
    description: Comma separated list of build names to filter build list on.
    required: false
  platform:
    description: Comma separated list of platforms to build for.
    required: false
  mode:
    description: Comma separated list of modes to build for. One of `{32, 64}.`
    required: false
  index:
    description: job index in matrix build
    required: true
  start_delay:
    description: |
      Maximum delay in seconds before the hardware run starts. The real delay at
      runtime is uniformly random in the interval `[0, start_delay]` to stagger
      board start-up times. Set to 0 to disable.
    required: false
    default: '60'
  action_name:
    description: 'internal -- do not use'
    required: false
    default: 'camkes-hw'

runs:
  using: 'node24'
  main: '../js/index.js'
  post: '../js/post.js'
