# Copyright 2020, Data61, CSIRO (ABN 41 687 119 230)
#
# SPDX-License-Identifier: BSD-2-Clause

name: 'License Check'
description: 'Runs the FSFE reuse license tool'
author: Gerwin Klein <gerwin.klein@csiro.au>

runs:
  using: 'node12'
  main: 'index.js'
