# Copyright 2021, Data61, CSIRO (ABN 41 687 119 230)
#
# SPDX-License-Identifier: BSD-2-Clause

name: 'thylint'
description: 'Runs the thylint tool on pull requests'
author: Gerwin Klein <kleing@unsw.edu.au>

inputs:
  token:
    description: 'GitHub token for read access to repository'
    required: false
  disable:
    description: 'Comma-separated list (no spaces) of warning classes to disable (default: none)'
    required: false

runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/steps.sh
      shell: bash
      env:
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_DISABLE: ${{ inputs.disable }}
