# Copyright 2021, Data61, CSIRO (ABN 41 687 119 230)
#
# SPDX-License-Identifier: BSD-2-Clause

name: 'thylint'
description: 'Runs the thylint tool on pull requests'
author: Gerwin Klein <gerwin.klein@csiro.au>

runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/steps.sh
      shell: bash
