# Copyright 2021, Data61, CSIRO (ABN 41 687 119 230)
#
# SPDX-License-Identifier: BSD-2-Clause

name: 'thylint'
description: 'Runs the thylint tool on pull requests'
author: Gerwin Klein <kleing@unsw.edu.au>

inputs:
  token:
    description: 'GitHub token for read access to repository'
    required: false
  pr_num:
    description: 'Explicit pull request number to check out, e.g. for pull_request_target'
    required: false
  disable:
    description: 'Comma-separated list (no spaces) of warning classes to disable (default: none)'
    required: false
  action_name:
    description: 'internal -- do not use'
    required: false
    default: 'thylint'

runs:
  using: 'node20'
  main: '../js/index.js'
