# Copyright 2020, Data61, CSIRO (ABN 41 687 119 230)
#
# SPDX-License-Identifier: BSD-2-Clause

name: 'Proofs'
description: |
  Runs the l4v proofs. Currently only the session CRefine.
author: Gerwin Klein <kleing@unsw.edu.au>

inputs:
  L4V_ARCH:
    description: 'Architecture to test. One of ARM, ARM_HYP, RISCV64, X64'
    required: true
  session:
    description: 'Which proof session to run'
    default: CRefine
    required: false
  isa_branch:
    description: 'Which branch/tag of the isabelle repository to use'
    required: false
  manifest:
    description: "Which manifest file to use (default devel.xml)"
    required: false

runs:
  using: 'docker'
  image: 'docker://sel4/run-proofs:latest'
