# Copyright 2021, Proofcraft Pty Ltd
#
# SPDX-License-Identifier: BSD-2-Clause

name: 'seL4Test/Hardware Matrices'
description: Generates build and run matrices for seL4Test.
author: Gerwin Klein <gerwin.klein@proofcraft.systems>

inputs:
  action_name:
    description: 'internal -- do not use'
    required: false
    default: 'sel4test-hw-matrix'

outputs:
  build_matrix:
    description: 'Hardware build matrix (JSON)'
  run_matrix:
    description: 'Hardware run matrix (JSON)'
  run_max_parallel:
    description: 'Number of base run matrix entries, for use as strategy.max-parallel'

runs:
  using: 'node24'
  main: '../js/index.js'
