#!/bin/bash
#
# Copyright 2016, Data61, CSIRO
#
# SPDX-License-Identifier: BSD-2-Clause
#
# For the isabelle-mirror action:
#
# Run system mercurial with:
# - built-in bookmarks extension.
# - clone bundling disabled.
# - sparse rev-logs disabled.
#
# We use the system hg with bundling disabled for compatibility with
# bitbucket.org.
# We disable sparse rev-logs for compatibility with our local installation
# of an old version of hg.

PATH="$IM_PATH_ORIG" exec /usr/bin/hg \
  --config "ui.clonebundles=false" \
  --config "extensions.hgext.bookmarks=" \
  --config "format.sparse-revlog=false" \
  "$@"
