# Copyright 2021, Proofcraft Pty Ltd
#
# SPDX-License-Identifier: BSD-2-Clause

name: 'RumpRun Hello World Hardware'
description: |
  The rumprun hello-world test on hardware.
author: Gerwin Klein <gerwin.klein@proofcraft.systems>

inputs:
  name:
    description: Comma separated list of build names to filter build list on.
    required: false
  req:
    description: Comma separated list of hardware to build for.
    required: false
  mode:
    description: Comma separated list of modes to build for. One of `{32, 64}.`
    required: false
  index:
    description: job index in matrix build
    required: true
  action_name:
    description: 'internal -- do not use'
    required: false
    default: 'rump-hello-hw'

runs:
  using: 'node12'
  main: '../js/index.js'
  post: '../js/post.js'
