# Copyright 2021, Proofcraft Pty Ltd
#
# SPDX-License-Identifier: BSD-2-Clause

name: 'seL4Test/Hardware Runs'
description: |
  Does sel4test test runs from previously built images for all hardware test platforms.
author: Gerwin Klein <gerwin.klein@proofcraft.systems>

inputs:
  arch:
    description: Comma separated list of architectures to filter test configs on.
    required: false
  march:
    description: Comma separated list of march flags to filter test configs on.
    required: false
  mode:
    description: Comma separated list of modes (32/64) to filter test configs on.
    required: false
  compiler:
    description: One of `{gcc, clang} to filter test configs on`
    required: false
  debug:
    description: |
      Comma separated list of debug levels from `{debug, release, verification}`
      to filter test configs on.
    required: false
  platform:
    description: Comma separated list of hardware platforms to run the test for.
    required: false
  index:
    description: job index in matrix build
    required: true
  action_name:
    description: 'internal -- do not use'
    required: false
    default: 'sel4test-hw-run'

runs:
  using: 'node12'
  main: '../js/index.js'
  post: '../js/post.js'
