# Copyright 2020, Data61, CSIRO (ABN 41 687 119 230)
#
# SPDX-License-Identifier: BSD-2-Clause

# Build and push docker image on changes to relevant files

name: Deploy

# Why deploy the builder image if it is supposed to be ephemeral? Because we
# couldn't get the docker GitHub action to refer to a local-only image, even
# with explicit build cache. Probably solvable, but this works as well, and it
# does build the builder only once, so it removes duplication for only mildly
# increased complexity.

on:
  push:
    branches:
    - master
    paths:
    - 'scripts/**'
    - 'docker/**'
    # trigger on anything the follow-on deployments might need as well:
    - 'seL4-platforms/**'
    - 'cparser-run/**'
    - 'preprocess/**'
  repository_dispatch:
    types: [cparser-deploy]
  workflow_dispatch:

jobs:
  docker:
    name: Docker (C Parser Builder)
    if: ${{ github.repository_owner == 'seL4' }}
    runs-on: ubuntu-latest
    steps:
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: docker/build-push-action@v2
      with:
        push: true
        file: docker/cparser-builder.dockerfile
        tags: sel4/cparser-builder:latest
    # this triggers the deployments that build on cparser-build:
    - uses: peter-evans/repository-dispatch@v1
      with:
          token: ${{ secrets.ISA_MIRROR_TOKEN }}
          event-type: cparser-build
