# Copyright 2021, Data61, CSIRO (ABN 41 687 119 230)
#
# SPDX-License-Identifier: BSD-2-Clause

# Scheduled Isabelle Mirror action

name: 'Isabelle Mirror'

on:
  schedule:
    - cron: '3 2 * * *'
  workflow_dispatch:

jobs:
  isabelle-mirror:
    name: 'Isabelle Mirror'
    if: ${{ github.repository_owner == 'seL4' }}
    runs-on: ubuntu-latest
    env:
      ISA_MIRROR_TOKEN: ${{ secrets.ISA_MIRROR_TOKEN }}
    steps:
    - uses: seL4/ci-actions/isabelle-mirror@master
