# Copyright 2020, Data61, CSIRO (ABN 41 687 119 230)
#
# SPDX-License-Identifier: BSD-2-Clause

# Actions to run on pull requests

name: PR

on:
  pull_request:
  workflow_call:
    secrets:
      token:
        description: 'Optional token for private repositories'
        required: false


jobs:
  gitlint:
    name: Gitlint
    runs-on: ubuntu-22.04
    steps:
    - uses: seL4/ci-actions/gitlint@master
      with:
        token: ${{ secrets.token }}

  whitespace:
    name: 'Trailing Whitespace'
    runs-on: ubuntu-latest
    steps:
    - uses: seL4/ci-actions/git-diff-check@master
      with:
        token: ${{ secrets.token }}

  shell:
    name: 'Portable Shell'
    runs-on: ubuntu-latest
    steps:
    - uses: seL4/ci-actions/bashisms@master
      with:
        token: ${{ secrets.token }}

  style:
    name: Style
    runs-on: ubuntu-22.04
    steps:
    - uses: seL4/ci-actions/style@master
      with:
        token: ${{ secrets.token }}
