# Copyright 2021, Proofcraft Pty Ltd
#
# SPDX-License-Identifier: BSD-2-Clause

# sel4test hardware builds and runs
#
# See sel4test-hw/builds.yml in the repo seL4/ci-actions for configs.

name: seL4Test-HW

on:
  workflow_call:

# intended to run on
#  pull_request_target:
#    types: [opened, reopened, synchronize, labeled]
# needs PR target for secrets access; guard by requiring label

# downgrade permissions to read-only as you would have in a standard PR action
permissions:
  contents: read

jobs:
  code:
    name: Freeze Code
    runs-on: ubuntu-latest
# Since we cancel older runs of this workflow for the current PR, we want to
# restart tests ("contains" clause), even if the event is for adding a different
# label.
    if: ${{ github.event_name == 'pull_request_target' &&
            (
              contains(github.event.pull_request.labels.*.name, 'hw-build') ||
              contains(github.event.pull_request.labels.*.name, 'hw-test') ||
              github.event.label.name == 'hw-build' ||
              github.event.label.name == 'hw-test'
            ) }}
    outputs:
      xml: ${{ steps.repo.outputs.xml }}
    steps:
    - id: repo
      uses: seL4/ci-actions/repo-checkout@master
      with:
        manifest_repo: sel4test-manifest
        manifest: master.xml
        sha: ${{ github.event.pull_request.head.sha }}

  hw-build:
    name: HW Build
    runs-on: ubuntu-latest
    needs: code
    # To reduce the load (especially on the machine queue) we cancel any older
    # runs of this workflow for the current PR.
    concurrency:
      group: ${{ github.workflow }}-sel4test-build-pr-${{ github.event.number }}-${{ strategy.job-index }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        # There is no "rv32imac" hardware yet.
        march: [armv7a, armv8a, nehalem, rv64imac]
        compiler: [gcc, clang]
    steps:
    - name: Build
      uses: seL4/ci-actions/sel4test-hw@master
      with:
        xml: ${{ needs.code.outputs.xml }}
        march: ${{ matrix.march }}
        compiler: ${{ matrix.compiler }}
    - name: Upload images
      uses: actions/upload-artifact@v4
      with:
        name: images-sel4test-${{ matrix.march }}-${{ matrix.compiler }}
        path: '*-images.tar.gz'
    - name: Upload kernel.elf files
      uses: actions/upload-artifact@v4
      with:
        name: kernel.elf-sel4test-${{ matrix.march }}-${{ matrix.compiler }}
        path: '*-kernel.elf'

  the_matrix:
    name: Matrix
    needs: hw-build
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
    - id: matrix
      uses: seL4/ci-actions/sel4test-hw-matrix@master

  hw-run:
    name: HW Run
    runs-on: ubuntu-latest
    needs: the_matrix
    if: ${{ github.repository_owner == 'seL4' &&
            (github.event_name == 'pull_request_target' &&
               (contains(github.event.pull_request.labels.*.name, 'hw-test') ||
                github.event.label.name == 'hw-test')) }}
    concurrency:
      group: ${{ github.workflow }}-sel4test-hw-run-pr-${{ github.event.number }}-${{ strategy.job-index }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.the_matrix.outputs.matrix) }}
    steps:
      - name: Get machine queue
        uses: actions/checkout@v4
        with:
          repository: seL4/machine_queue
          path: machine_queue
      - name: Download image
        uses: actions/download-artifact@v4
        with:
          name: images-sel4test-${{ matrix.march }}-${{ matrix.compiler }}
      - name: Run
        uses: seL4/ci-actions/sel4test-hw-run@master
        with:
          platform: ${{ matrix.platform }}
          compiler: ${{ matrix.compiler }}
          mode: ${{ matrix.mode }}
          index: $${{ strategy.job-index }}
        env:
          HW_SSH: ${{ secrets.HW_SSH }}
