# Copyright 2020, Data61, CSIRO (ABN 41 687 119 230)
#
# SPDX-License-Identifier: BSD-2-Clause

# Actions to run on pull requests

name: X

on: [pull_request]

jobs:
  preprocess:
    name: 'first'
    runs-on: ubuntu-latest
    steps:
    - run: exit 1

  proofs:
    name: 'second'
    if: failure()
    needs: preprocess
    runs-on: ubuntu-latest
    steps:
    - run: echo second
