# Copyright 2020, Data61, CSIRO (ABN 41 687 119 230)
#
# SPDX-License-Identifier: BSD-2-Clause

# Actions to run on pull requests

name: X

on: [pull_request]

jobs:
  other:
    name: 'other'
    runs-on: ubuntu-latest
    steps:
    - run: exit 1

  preprocess:
    name: 'first'
    runs-on: ubuntu-latest
    steps:
    - run: sleep 5; exit 0

  proofs:
    name: 'second'
    needs: preprocess
    if: failure()
    runs-on: ubuntu-latest
    steps:
    - if: needs.preprocess.result == 'failure'
      run: echo 1 failed
    - if: needs.preprocess.result != 'failure'
      run: echo skipped